# Generated by Django 5.0.7 on 2024-07-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_product_warehouse_sale_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
